apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}

